version: '3.9'

services:

  comrade-db:
    image: "postgres:16.4-bullseye"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - "5433:5432"