version: '3.9'

services:

  flask-db:
    image: "postgres:16.4-bullseye"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: $POSTGRES_USER
      POSTGRES_USER: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"