table = "dim_product"
schema = "olap"
database = "olap_db"

[fields]
id = {field_type = "service_key", alias = "product_id_alias", front_name="none", data_type="number"}
product = {field_type = "dimension", alias = "product_alias", front_name="Название товара", use_sk_for_count="True", data_type="text"}
